src/Snppts/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Snppts.Controllers;

public class HomeController : BaseController
{
    private readonly IAmASnippet[] _snippets;

    public HomeController(IEnumerable<IAmASnippet> snippets)
    {
        _snippets = snippets.ToArray();
    }

    [Route("")]
    public IActionResult Index(int? page)
    {
        var pageNumber = page ?? 1;
        var viewModel = _snippets.ToPagedList(pageNumber, 9);

        return View(viewModel);
    }

    [Route("about")]
    public IActionResult About()
    {
        return View();
    }

    [Route("how-to-contribute")]
    public IActionResult Contributing()
    {
        return View();
    }

    //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    //public IActionResult Error()
    //{
    //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    //}
}

src/Snppts/ViewComponents/RandomSnippetsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Snppts.ViewComponents;

public class RandomSnippetsViewComponent : ViewComponent
{
    private readonly IEnumerable<IAmASnippet> _snippets;

    public RandomSnippetsViewComponent(IEnumerable<IAmASnippet> snippets)
    {
        _snippets = snippets.ToArray();
    }

    public IViewComponentResult Invoke()
    {
        var random = new Random();
        var snippets = _snippets.OrderBy(x => random.Next()).Take(3).ToList();

        return View(snippets);
    }
}

src/Snppts/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
ViewBag.Description = "This is Snppts! Learn some more about us.";
Layout = "~/Views/Shared/_LayoutNoSidebar.cshtml";
}

<section class="main-container">
    <div class="container">
        <div class="row">
            <div class="main col-md-12">
                <h1 class="page-title">About Us</h1>
                <div class="separator-2 mb-20"></div>
                <div class="row mb-40">
                    <div class="col-md-12">
                        <p>
                            Snppts was founded by two Xamarin addicts from the Netherlands. You know... That place near Holland. We take a great
                            interest in creating (re)useable and good-looking UI designs and in recent times the Xamarin community seems to have done the same.
                            Therefore, we decided to create a platform where developers and designers from all over the world can come together and share their beautiful work.
                            That way all of us can benefit and we can spread the Xamarin message even further!
                        </p>
                        <p>
                            We hope that you will enjoy using Snppts and will join us in creating awesome UIs for mobile apps and share your knowledge with the rest of the world.
                            If there is anything you would like to see changed, compliment us or just want to say hi you can reach us on Twitter.
                        </p>
                        <p>
                            Snppts is founded by Steven Thewissen (<a href="https://twitter.com/devnl" target="_blank">@@devnl</a>) and Gerald Versluis (<a href="https://twitter.com/jfversluis" target="_blank">@@jfversluis</a>).
                        </p>
                    </div>
                </div>
                <div class="row">
                    @await Component.InvokeAsync("RandomSnippets")
                </div>
            </div>
        </div>
    </div>
</section>


@section precontent
    {
    <!-- banner start -->
    <!-- ================ -->
    <div class="banner dark-translucent-bg" style="background-image:url('img/background.jpg'); background-position: 50% 27%;">
        <div class="container">
            <div class="row">
                <div class="col-md-8 text-center col-md-offset-2 pv-20">
                    <img src="~/img/snppts_logo_white.png" class="title about-logo object-non-visible" data-animation-effect="fadeIn" data-effect-delay="100" />
                    <div class="separator object-non-visible mt-10" data-animation-effect="fadeIn" data-effect-delay="100"></div>
                    <p class="text-center object-non-visible" data-animation-effect="fadeIn" data-effect-delay="100">
                        So you want to know more about us? Even get to know us? You've come to the right place!
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- banner end -->
}

@section scripts{
    <script type="text/javascript" src="~/plugins/waypoints/jquery.waypoints.min.js"></script>
}

src/Snppts/Views/Home/Contributing.cshtml
@{
    ViewBag.Title = "How to Contribute";
ViewBag.Description = "Want to submit your own Snppts? Here's how!";
Layout = "~/Views/Shared/_LayoutNoSidebar.cshtml";
}

<section class="main-container">
    <div class="container">
        <div class="row">
            <div class="main col-md-12">
                <h1 class="page-title">How to Contribute</h1>
                <div class="separator-2 mb-20"></div>
                <div class="row">
                    <div class="col-md-12">
                        <p>If you create cool UIs in .NET MAUI or Xamarin, this is the place to be! You're welcome to add your created UIs and become part of our ever-growing library of content! Please keep in mind that what you are sharing does not violate the community <a href="https://github.com/snpptsdev/snppts/blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.</p>

                        <h3>Add yourself as an author</h3>
                        <div class="separator-2 mb-20"></div>
                        <p>To add yourself as a Snppts author you can fork this project, add yourself to the authors folder as a class, implementing the <strong>IAmAnAuthor</strong> interface.</p>
                        <p>The result should look something like this:</p>
                        <script src="https://gist.github.com/sthewissen/83e363a44d6fb573edbaefae43c6daba.js"></script>
                        <p>
                            A few pointers:
                            <ul>
                                <li>Name the class after your first and lastname with PascalCase.</li>
                                <li>The FirstName and LastName property should resemble that same name.</li>
                                <li>EmailAddress, TwitterHandle and GitHubHandle should be pretty clear, TwitterHandle without the leading @@.</li>
                                <li>The Website property can be your global website or whatever you want people to look at.</li>
                                <li>If you want to show your Gravatar go to https://en.gravatar.com/site/check/ and get your hash! If you don't fill the hash, you will be viewed as a silhouette.</li>
                            </ul>
                        </p>
                        <h3>Add your first snippet</h3>
                        <div class="separator-2 mb-20"></div>
                        <p>
                            To add a snippet you can fork this project, add your snippet to the <strong>Snippets</strong> folder as a class, implementing the <strong>IAmASnippet</strong> interface.
                        </p>
                        <p>
                            The result should look something like this:
                        </p>
                        <script src="https://gist.github.com/sthewissen/461644f3b6b0bc84c194bdaa62c91001.js"></script>
                        <p>
                            A few pointers:
                            <ul>
                                <li>Name the class after the title of your snippet with PascalCase.</li>
                                <li>Provide a slug where your creation should be permalinked on Snppts.</li>
                                <li>Link your <strong>IAmAnAuthor</strong> object by creating a new instance of it. This allows you to post more snippets in the future!</li>
                                <li>Choose one or more appropriate categories for your creation. If there's no existing category that fits your creation you're allowed to add one but it will be reviewed upon submitting your PR.</li>
                                <li>With ImageUris you can supply one or more URIs showing off screenshots of your creation. Please make sure that these screenshots are all of a single screen, so no compilations.</li>
                            </ul>
                        </p>
                        <h3>.NET MAUI and Xamarin only please</h3>
                        <div class="separator-2 mb-20"></div>
                        <p>
                            This site is dedicated to .NET MAUI and Xamarin, so samples in Swift, Java, Objective-C and the likes will not be accepted. Since we will be looking at each PR we will reject any that are not about .NET MAUI or Xamarin.
                        </p>
                        <h3>The last step</h3>
                        <div class="separator-2 mb-20"></div>
                        <p>
                            A big step for monkeykind 🐵! Last thing that remains is submit a Pull Request to us and whenever it gets merged 🎉! You're on Snppts now!
                        </p>
                        <img class="mb-20" src="~/img/snppts-badge.jpg" />
                        <p>
                            Don't forget to incorporate the <strong>Featured on Snppts</strong> badge on your blog and link back to us! Enjoy all of our great content! Of course you are more than welcome to submit other features and bugfixes as well.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/Snppts/Views/Home/Index.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using X.PagedList;

@model IEnumerable<Snppts.Infrastructure.IAmASnippet>

@{ ViewBag.Title = "Welcome to Snppts";
            ViewBag.Description = "A selection of Xamarin.Forms UI snippets for use in your own apps!"; }

@if (Model.Count() > 0)
{
<div class="row">
    <h3 class="title">Our snippets</h3>
    <div class="separator-2"></div>
    @{ var count = 0; }

    <div class="row">
        @foreach (var item in Model)
    {
        if (count % 3 == 0)
        {
@Html.Raw("</div><div class=\"row\">") }

                count += 1;

<partial name="Partials/_SnippetListItem" model="@item" />}
    </div>
</div>
            <div class="row pager">
                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions()
                {
                    LinkToNextPageFormat = "»",
                    LinkToPreviousPageFormat = "«",
                    DisplayLinkToFirstPage = PagedListDisplayMode.Never,
                    DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
                    DisplayLinkToLastPage = PagedListDisplayMode.Never,
                    DisplayLinkToNextPage = PagedListDisplayMode.IfNeeded,
                    MaximumPageNumbersToDisplay = 0,
                    DisplayEllipsesWhenNotShowingAllPageNumbers = false
                })
                </div> }
                        else
                        {
            <div class="row">
                    <div class="main col-md-6 col-md-offset-3 pv-40">
                        <h2>Oops... No snippets found!</h2>
                        <p>
                            We searched high and low but absolutely no snippets were found. You can always submit your own snippets!
                            Want to know how? Learn more on our "How to Contribute" page.
                        </p>
                        <a asp-area="" asp-controller="Index" asp-action="Contributing" class="btn btn-default btn-animated">Contribute <i class="fa fa-edit"></i></a>
                    </div>
                </div>}