src/Snppts/ViewComponents/AllCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Snppts.ViewComponents;

public class AllCategoriesViewComponent : ViewComponent
{
    private readonly IEnumerable<IAmASnippet> _snippets;

    public AllCategoriesViewComponent(IEnumerable<IAmASnippet> snippets)
    {
        _snippets = snippets.ToArray();
    }

    public IViewComponentResult Invoke()
    {
        var categories = _snippets.Select(x => x.Categories).SelectMany(i => i);
        var groupedSorted = categories.GroupBy(n => n).OrderBy(g => g.FirstOrDefault().ToString());
        var categoriesFinal = groupedSorted.Select(x => x.FirstOrDefault()).ToList();

        return View(categoriesFinal);
    }
}

src/Snppts/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions;

@{
    var url = Context.Request.GetDisplayUrl();
}
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-43277628-11"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-43277628-11');
    </script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta name="description" content="Snppts - A .NET MAUI and Xamarin.Forms UI snippet library">
    <meta name="author" content="snppts.dev">
    <meta name="keywords" content=".NET MAUI, MAUI, Xamarin, Forms, Xaml, code, snippets, design, UI, snppts, share, developers">
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="7 days" />

    <link rel="apple-touch-icon" sizes="180x180" href="~/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/favicon-16x16.png">
    <link rel="manifest" href="~/img/site.webmanifest">
    <link rel="mask-icon" href="~/img/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="~/img/favicon.ico">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="msapplication-config" content="~/img/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- OpenGraph tags -->
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:url" content="@url" />
    <meta property="og:description" content="@ViewBag.Description" />
    <meta property="og:image" content="https://www.snppts.dev/img/social.png" />

    <!-- Twitter tags -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@("@")snpptsio)" />
    <meta name="twitter:site" content="@("@")snpptsio)" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:url" content="@url" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="https://www.snppts.dev/img/social.png" />


    <link href='//fonts.googleapis.com/css?family=Nunito+Sans:700,400,300' rel='stylesheet' type='text/css'>

    <title>Snppts - @ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/fonts/fontello/css/fontello.css" />

    <link href="~/css/project/style.css" rel="stylesheet" />
    <link href="~/css/project/cool_green.css" rel="stylesheet" />
    <link href="~/css/project/animate.css" rel="stylesheet" />
    <link href="~/css/project/animations.css" rel="stylesheet" />
    <link href="~/css/project/hover-min.css" rel="stylesheet" />
    <link href="~/css/project/custom.css" rel="stylesheet" />

    @RenderSection("styles", required: false)
</head>
<body class="no-trans transparent-header">
    <img src="~/img/beta.png" class="snippet-beta" />

    <!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>

    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">
        <partial name="Partials/_Header" />
        <section class="main-container">
            <div class="container snippet-main-container">
                <div class="row">
                    <aside class="col-md-2 hidden-sm hidden-xs">
                        <div class="sidebar">
                            <div class="block clearfix">
                                @await Component.InvokeAsync("AllCategories")
                            </div>
                        </div>
                    </aside>
                    <div class="main col-md-10">
                        @RenderBody()
                    </div>
                    <aside class="col-md-2 hidden-md hidden-lg">
                        <div class="sidebar">
                            <div class="block clearfix">
                                @await Component.InvokeAsync("AllCategories")
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </section>

        <partial name="Partials/_Footer" />
    </div>

    <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <!-- SmoothScroll javascript -->
    <script type="text/javascript" src="~/plugins/jquery.browser.js"></script>
    <script type="text/javascript" src="~/plugins/SmoothScroll.js"></script>

    <!-- Initialization of Plugins -->
    <script type="text/javascript" src="~/plugins/modernizr.js"></script>
    <script type="text/javascript" src="~/js/template.js"></script>

    <!-- Custom Scripts -->
    <script type="text/javascript" src="~/js/custom.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

src/Snppts/Views/Shared/_LayoutNoSidebar.cshtml
@using Microsoft.AspNetCore.Http.Extensions;

@{
    var url = Context.Request.GetDisplayUrl();
}
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-43277628-11"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-43277628-11');
    </script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta name="description" content="Snppts - A .NET MAUI and Xamarin.Forms UI snippet library">
    <meta name="author" content="snppts.dev">
    <meta name="keywords" content=".NET MAUI, MAUI, Xamarin, Forms, Xaml, code, snippets, design, UI, snppts, share, developers">
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="7 days" />

    <!-- OpenGraph tags -->
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:url" content="@url" />
    <meta property="og:description" content="@ViewBag.Description" />
    <meta property="og:image" content="https://www.snppts.dev/img/social.png" />

    <!-- Twitter tags -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@("@")snpptsio)" />
    <meta name="twitter:site" content="@("@")snpptsio)" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:url" content="@url" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="https://www.snppts.dev/img/social.png" />

    <link href='//fonts.googleapis.com/css?family=Nunito+Sans:700,400,300' rel='stylesheet' type='text/css'>

    <title>Snppts - @ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/fonts/fontello/css/fontello.css" />

    <link href="~/css/project/style.css" rel="stylesheet" />
    <link href="~/css/project/cool_green.css" rel="stylesheet" />
    <link href="~/css/project/animate.css" rel="stylesheet" />
    <link href="~/css/project/animations.css" rel="stylesheet" />
    <link href="~/css/project/hover-min.css" rel="stylesheet" />
    <link href="~/css/project/custom.css" rel="stylesheet" />


    @RenderSection("styles", required: false)
</head>
<body class="no-trans transparent-header">
    <img src="~/img/beta.png" class="snippet-beta" />

    <!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>

    <!-- page wrapper start -->
    <!-- ================ -->
    <div class="page-wrapper">
        <partial name="Partials/_Header" />

        @RenderSection("precontent", false)

        @RenderBody()

        <partial name="Partials/_Footer" />
    </div>

    <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <!-- SmoothScroll javascript -->
    <script type="text/javascript" src="~/plugins/jquery.browser.js"></script>
    <script type="text/javascript" src="~/plugins/SmoothScroll.js"></script>

    <!-- Initialization of Plugins -->
    <script type="text/javascript" src="~/plugins/modernizr.js"></script>
    <script type="text/javascript" src="~/js/template.js"></script>

    <!-- Custom Scripts -->
    <script type="text/javascript" src="~/js/custom.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>