src/Snppts/Controllers/SnippetsController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Snppts.Controllers;

public class SnippetsController : BaseController
{
    private readonly IAmASnippet[] _snippets;

    public SnippetsController(IEnumerable<IAmASnippet> snippets)
    {
        _snippets = snippets.ToArray();
    }

    [Route("category/{id}")]
    public IActionResult Category(int id, int? page)
    {
        var pageNumber = page ?? 1;
        var viewModel = _snippets.Where(x => x.Categories.Contains((Category)id)).ToPagedList(pageNumber, 9);
        return View(viewModel);
    }

    [Route("author/{githubhandle}")]
    public IActionResult Author(string gitHubHandle, int? page)
    {
        var pageNumber = page ?? 1;
        var viewModel = _snippets.Where(x => x.AuthorInfo.GitHubHandle.ToLower().Equals(gitHubHandle.ToLower())).ToPagedList(pageNumber, 9);
        return View(viewModel);
    }

    [Route("sort/{sorttype}")]
    public async Task<IActionResult> Sort(SortType sortType, int? page)
    {
        var pageNumber = page ?? 1;
        var sort = await _snippets.SortSnippets(sortType, pageNumber);
        var viewModel = new StaticPagedList<IAmASnippet>(sort, pageNumber, 30, sort.Count);

        var title = "";

        switch (sortType)
        {
            case SortType.stars:
                title = "Most starred";
                break;
            case SortType.updated:
            default:
                title = "Most recent";
                break;
        }

        return View(new SnpptsControllerAux
        {
            Snppets = viewModel,
            TitlePage = title
        });
    }

    [Route("random")]
    public IActionResult Random()
    {
        var random = new Random();
        var randomSnip = _snippets.OrderBy(x => random.Next()).FirstOrDefault();

        if (randomSnip != null)
            return RedirectToAction("Show", new { slug = randomSnip.Slug });

        // No luck, so back home.
        return RedirectToAction("Index", "Home");
    }

    [Route("snippet/{slug}")]
    public IActionResult Show(string slug)
    {
        var viewModel = _snippets.FirstOrDefault(x => x.Slug == slug);

        if (viewModel != null)
            return View(viewModel);

        // No luck, so back home.
        return RedirectToAction("Index", "Home");
    }
}

public class SnpptsControllerAux
{
    public IEnumerable<IAmASnippet> Snppets { get; set; }

    public string TitlePage { get; set; }
}

src/Snppts/ViewComponents/PopularCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Snppts.ViewComponents;

public class PopularCategoriesViewComponent : ViewComponent
{
    private readonly IEnumerable<IAmASnippet> _snippets;

    public PopularCategoriesViewComponent(IEnumerable<IAmASnippet> snippets)
    {
        _snippets = snippets.ToArray();
    }

    public IViewComponentResult Invoke()
    {
        var categories = _snippets.Select(x => x.Categories).SelectMany(i => i);
        var groupedSorted = categories.GroupBy(n => n).OrderByDescending(g => g.Count());
        var categoriesFinal = groupedSorted.Take(10).Select(x => x.FirstOrDefault()).ToList();

        return View(categoriesFinal);
    }
}

src/Snppts/Views/Shared/Partials/_Footer.cshtml
<footer id="footer" class="clearfix ">
    <!-- .footer start -->
    <!-- ================ -->
    <div class="footer">
        <div class="container">
            <div class="footer-inner">
                <div class="row">
                    <div class="col-md-3">
                        <div class="footer-content">
                            <div class="logo-footer"><img id="logo-footer" class="logo-sized" src="~/img/snppts_logo.png" alt=""></div>
                            <p>
                                Snppts lets .NET MAUI and Xamarin.Forms developers and designers share interface snippets to enable each other to
                                quickly create great looking mobile apps for Android, iOS, macOS and Windows.
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="footer-content">
                            <h2 class="title">Learn more</h2>
                            <div class="separator-2"></div>
                            <nav>
                                <ul class="nav nav-pills nav-stacked">
                                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                                    <li><a href="https://twitter.com/snpptsdev">Twitter</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="footer-content">
                            <h2 class="title">On this site</h2>
                            <div class="separator-2"></div>
                            <nav>
                                <ul class="nav nav-pills nav-stacked">
                                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Snippets</a></li>
                                    <li><a asp-area="" asp-controller="Snippets" asp-action="Random">Surprise me!</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Contributing">How to Contribute</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="footer-content">
                            <h2 class="title">Popular categories</h2>
                            <div class="separator-2"></div>
                            @await Component.InvokeAsync("PopularCategories")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- .footer end -->
    <!-- .subfooter start -->
    <!-- ================ -->
    <div class="subfooter dark-bg">
        <div class="container">
            <div class="subfooter-inner">
                <div class="row">
                    <div class="col-md-12">
                        <p class="text-center">Copyright &copy; 2017-@DateTime.Now.Year Snppts by <a target="_blank" class="link-light" href="http://www.snppts.dev">snppts.dev</a>. All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- .subfooter end -->
</footer>

src/Snppts/Views/Shared/Partials/_Header.cshtml
<!-- header-container start -->
<div class="header-container">
    <header class="header fixed clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="header-left clearfix">

                        <div id="logo" class="logo">
                            <a  asp-area="" asp-controller="Home" asp-action="Index"><img id="logo_img" class="logo-sized" src="~/img/snppts_logo.png" alt="Snppts"></a>
                        </div>

                        <div class="site-slogan">
                            .NET MAUI &amp; Xamarin.Forms UI Snippets
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="header-right clearfix">
                        <div class="main-navigation  animated">
                            <nav class="navbar navbar-default" role="navigation">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                    <div class="collapse navbar-collapse" id="navbar-collapse-1">
                                        <ul class="nav navbar-nav ">
                                            <li>
                                                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Snippets" asp-action="Random">Surprise me!</a>
                                            </li>
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sort By</a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="/">Default</a></li>
                                                    <li><a href="/sort/updated">Recent</a></li>
                                                    <li><a href="/sort/stars">Stars</a></li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Home" asp-action="Contributing">How to Contribute</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                                            </li>
                                            <li>
                                                <a class="cta" href="https://www.github.com/snpptsdev/snppts" target="_blank">Contribute now!</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

src/Snppts/Views/Shared/Partials/_ScreenshotSlider.cshtml
@model IEnumerable<Uri>

<div class="description__section">
    <h5>Screenshots</h5>

    <div class="row">
        @foreach (var screenshot in Model)
    {
        <div class="col-md-3 snippet__screenshot">
                <a href="@screenshot.AbsoluteUri" target="_blank">
                    <img src="@screenshot.AbsoluteUri" alt="">
                </a>
            </div>
    }
    </div>
</div>

src/Snppts/Views/Shared/Partials/_SnippetListItem.cshtml
@model Snppts.Infrastructure.IAmASnippet

<div class="col-lg-4 col-md-4 col-sm-6 margin-bottom-20 snppt">

    @if (Model.ImageUris.Any())
{
    <a asp-area="" asp-controller="Snippets" asp-action="Show" asp-route-slug="@Model.Slug"><img class="snippet__img" src="@Model.ImageUris.FirstOrDefault().AbsoluteUri" /></a>
}

    <h4 class="text-center"><a asp-area="" asp-controller="Snippets" asp-action="Show" asp-route-slug="@Model.Slug">@Model.Title</a></h4>

    <p class="tags text-center">
        @string.Join(", ", Model.Categories).ToUpper()
    </p>

    <div class="text-center margin-bottom-20 platform-icons">
        @if (Model.ContainsiOSSample)
    {
        <i class="fa fa-apple"></i>
    }
        @if (Model.ContainsAndroidSample)
    {
        <i class="fa fa-android"></i>
    }
        @if (Model.ContainsUWPSample)
    {
        <i class="fa fa-windows"></i>
    }
        @if (Model.GitHubRepoInfo.GetRepoInfoFromService(Snppts.Extensions.SortExtention.GitHubRepos)?.Stars > 0)
    {
        <i class="fa fa-star"></i><b class="text">@Model.GitHubRepoInfo.GetRepoInfoFromService(Snppts.Extensions.SortExtention.GitHubRepos).Stars</b>
    }
    @*@if (Model.GitHubRepoInfo.GetRepoInfo(Snppts.Extensions.SortExtention.GitHubRepos)?.UpdatedAt != null)
            {
                <p>
                    <span style="text-transform:uppercase; font-weight:bold; font-size:xx-small"> @Model.GitHubRepoInfo.GetRepoInfo(Snppts.Extensions.SortExtention.GitHubRepos).UpdatedAt.ToString("MMM/yyyy")</span>
                </p>
            }*@
    </div>
</div>